### ISSUE TITLE
Thoughts on a multi master postgres setup ?

### ISSUE THREAD

**Issue by pascalandy** [codedellemc/labs#2]
Hey guys,

In a perfect world, I would have 3 worker nodes, each running one pgsql instance. Each of them would be master (not master-slave-slave). In this setup I could:
- load balance the db request to the 3 db instances.
- detroy a postgres node and relaunch a new one without fuzz, whatever it was a crash or for any kind of update 

**Question** - Do you see a way to have a have a multi master setup for postgres via Docker Swarm? This is a big deal. I'm still wondering if a volume over the network like rexray is the solution.

---

Saw this project via Nathan Leclair's tweet https://twitter.com/upthecyberpunks/status/773295898608693248

I use https://github.com/sameersbn/docker-postgresql

Cheers!
Pascal [twitter](https://twitter.com/_pascalandy)

**Comment by kacole2** [comment]
hey @pascalandy i think we had talked over my blog post once. Have you had a chance to test it out? Any errors you're getting? 

I don't know much about multi-master Postgres. Are all 3 nodes sharing the same volume/back-end storage? Or do they each have their own and replicate between one another?

**Comment by pascalandy** [comment]
Never tested this yet. So far the most promising project is https://github.com/citusdata/citus
