### ISSUE TITLE
failed to start container

### ISSUE THREAD

**Issue by bottkars** [codedellemc/labs#31]
kubectl logs $RRPOD
`/bin/sh: $'[\342\200\234rexray-controller\342\200\235,': command not found`

**Comment by bottkars** [comment]
works with 0.8.1 cduchesne/rexray-controller

**Comment by kacole2** [comment]
thanks! someone else in the slack channel had that same issue. I'll make a note of it to change it. 

There will also be a new ScaleIO + Kubernetes 1.6 Vagrant Demo that will be ready this week. so stay tuned!

**Comment by bottkars** [comment]
apparently there is a tool, called labbiuildr, does this on Workstation :-) https://github.com/bottkars/labbuildr/wiki/ubuntu-bakery.ps1#kubernetes
had to move towards 1.6.1 as 1.6 had BIG issues. with 1.6.1 and rbac it seems fine now ( i am using flannel )
