### ISSUE TITLE
S3FS, EBS plugins should not require accessKey and secretKey if IAM roles allow access

### ISSUE THREAD

**Issue by ghost** [codedellemc/labs#36]
For enterprise policy where access and secret keys are prohibited and IAM roles provide authorization to EBS, S3 resources as required, these keys should not be required.

**Comment by ghost** [comment]
no rexray issue queue :(

**Comment by kacole2** [comment]
@jpgbus yes you can opt to use IAM profiles over access/secret keys. These are all in the REX-Ray documentation.
